<?php

namespace AestheticCart\Install;

class DemoDataTables
{
    /**
     * Content tables exported/imported for demo storefront data.
     * Excludes users, orders, sessions, and queue tables.
     *
     * @return list<string>
     */
    public static function content(): array
    {
        return [
            'addresses',
            'attribute_categories',
            'attribute_set_translations',
            'attribute_sets',
            'attribute_translations',
            'attribute_value_translations',
            'attribute_values',
            'attributes',
            'beautician_blocked_times',
            'beautician_spa_branch',
            'beautician_working_hours',
            'beauticians',
            'blog_categories',
            'blog_category_translations',
            'blog_post_blog_tag',
            'blog_post_translations',
            'blog_posts',
            'blog_tag_translations',
            'blog_tags',
            'brand_translations',
            'brands',
            'categories',
            'category_translations',
            'coupon_categories',
            'coupon_products',
            'coupon_translations',
            'coupons',
            'cross_sell_products',
            'currency_rates',
            'entity_files',
            'files',
            'flash_sale_product_orders',
            'flash_sale_products',
            'flash_sale_translations',
            'flash_sales',
            'loyalty_tiers',
            'menu_item_translations',
            'menu_items',
            'menu_translations',
            'menus',
            'meta_data',
            'meta_data_translations',
            'option_translations',
            'option_value_translations',
            'option_values',
            'options',
            'page_translations',
            'pages',
            'product_attribute_values',
            'product_attributes',
            'product_categories',
            'product_options',
            'product_tags',
            'product_translations',
            'product_variants',
            'product_variations',
            'products',
            'related_products',
            'setting_translations',
            'settings',
            'slider_slide_translations',
            'slider_slides',
            'slider_translations',
            'sliders',
            'spa_branches',
            'tag_translations',
            'tags',
            'tax_class_translations',
            'tax_classes',
            'tax_rate_translations',
            'tax_rates',
            'translation_translations',
            'translations',
            'treatment_categories',
            'up_sell_products',
            'variation_translations',
            'variation_value_translations',
            'variation_values',
            'variations',
        ];
    }
}
