<?php

$appUrl = rtrim((string) env('APP_URL', 'http://localhost'), '/');
$waLine = '..............................................................';

return [
  /*
    |--------------------------------------------------------------------------
    | WhatsApp / OneSender (Settings → tab=sms)
    |--------------------------------------------------------------------------
    | Override via .env. Applied to DB when missing/null (see migration).
    */
    'onesender_enabled' => filter_var(env('ONESENDER_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'onesender_api_url' => env('ONESENDER_API_URL', 'https://wa3269.cloudwa.my.id/api/v1/messages'),
    'onesender_api_key' => env('ONESENDER_API_KEY', ''),
    'onesender_admin_phones' => env('ONESENDER_ADMIN_PHONES', ''),
    'onesender_whatsapp_group_id' => env('ONESENDER_WHATSAPP_GROUP_ID', ''),
    'onesender_sending_paused' => filter_var(env('ONESENDER_SENDING_PAUSED', false), FILTER_VALIDATE_BOOLEAN),
    'onesender_dedupe_enabled' => filter_var(env('ONESENDER_DEDUPE_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'onesender_dedupe_minutes' => (int) env('ONESENDER_DEDUPE_MINUTES', 1440),
    'onesender_outbound_queue_enabled' => filter_var(env('ONESENDER_OUTBOUND_QUEUE_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'onesender_outbound_delay_seconds' => (int) env('ONESENDER_OUTBOUND_DELAY_SECONDS', 30),
    // Block real WhatsApp sends on APP_ENV=local unless explicitly enabled (prevents dev/tinker accidents).
    'onesender_allow_in_local' => filter_var(env('ONESENDER_ALLOW_IN_LOCAL', false), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_group_staff_name' => env('WHATSAPP_GROUP_STAFF_NAME', 'TEAM'),
    'whatsapp_order_tracking_url' => env(
        'WHATSAPP_ORDER_TRACKING_URL',
        $appUrl . '/order-tracking'
    ),

    'welcome_sms' => filter_var(env('WHATSAPP_WELCOME_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_welcome_message' => env('WHATSAPP_WELCOME_MESSAGE', implode("\n", [
        'Hai :first_name,',
        '',
        'Akaun anda di *:store* telah berjaya didaftarkan.',
        '',
        'Terima kasih!',
    ])),
    'whatsapp_customer_reminder_enabled' => filter_var(env('WHATSAPP_CUSTOMER_REMINDER_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_customer_reminder_minutes' => (int) env('WHATSAPP_CUSTOMER_REMINDER_MINUTES', 60),
    'whatsapp_customer_reminder_message' => env('WHATSAPP_CUSTOMER_REMINDER_MESSAGE', implode("\n", [
        '⏰ *Peringatan Temujanji — :store*',
        '',
        'Hai :customer,',
        '',
        'Rawatan: :treatment',
        'Tarikh: :date',
        'Masa: :time',
        ':extra_lines',
        '',
        'Sila hadir tepat pada masa. Terima kasih!',
    ])),
    'whatsapp_customer_completed_enabled' => filter_var(env('WHATSAPP_CUSTOMER_COMPLETED_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_customer_completed_message' => env('WHATSAPP_CUSTOMER_COMPLETED_MESSAGE', implode("\n", [
        '✨ *Terima Kasih — :store*',
        '',
        'Hai :customer,',
        '',
        'Rawatan *:treatment* anda telah selesai.',
        '',
        'Kami berharap anda berpuas hati. Jumpa lagi!',
    ])),
    'whatsapp_customer_followup_enabled' => filter_var(env('WHATSAPP_CUSTOMER_FOLLOWUP_ENABLED', false), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_customer_followup_days' => (int) env('WHATSAPP_CUSTOMER_FOLLOWUP_DAYS', 7),
    'whatsapp_customer_followup_message' => env('WHATSAPP_CUSTOMER_FOLLOWUP_MESSAGE', implode("\n", [
        '💆 *Susulan — :store*',
        '',
        'Hai :customer,',
        '',
        'Sudah :date sejak rawatan *:treatment* anda. Bagaimana keadaan anda?',
        '',
        'Hubungi kami jika ingin tempah sesi seterusnya. Terima kasih!',
    ])),

    'new_order_admin_sms' => filter_var(env('WHATSAPP_NEW_ORDER_ADMIN', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_new_order_admin_message' => env('WHATSAPP_NEW_ORDER_ADMIN_MESSAGE', implode("\n", [
        '🛒 *Pesanan Baharu — :store*',
        '',
        'Order No : :order_id',
        'Customer : :customer',
        'Email : :email',
        'Phone : :phone',
        'Order Date : :order_date',
        $waLine,
        'Beautician : :beautician',
        'Appt.Date: :appointment_date',
        'Appt.Time: :appointment_time',
        $waLine,
        'Items :',
        ':treatments',
        ':payment_summary',
    ])),
    'new_order_sms' => filter_var(env('WHATSAPP_NEW_ORDER_CUSTOMER', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_new_order_customer_message' => env('WHATSAPP_NEW_ORDER_CUSTOMER_MESSAGE', implode("\n", [
        'Hai :first_name,',
        '',
        'Terima kasih! Pesanan anda di *:store* telah diterima. 🎉',
        '',
        'Order No : :order_id',
        'Order Date : :order_date',
        $waLine,
        'Beautician : :beautician',
        'Appt.Date: :appointment_date',
        'Appt.Time: :appointment_time',
        $waLine,
        'Items :',
        ':treatments',
        ':payment_summary',
        '',
        'Jejak pesanan: :tracking_url',
    ])),
    'whatsapp_order_status_message' => env('WHATSAPP_ORDER_STATUS_MESSAGE', implode("\n", [
        'Hai :first_name,',
        '',
        'Status pesanan #:order_id anda telah ditukar kepada :status.',
    ])),
    'sms_order_statuses' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('WHATSAPP_SMS_ORDER_STATUSES', 'pending,processing,completed'))
    ))),

    'whatsapp_completed_group_enabled' => filter_var(env('WHATSAPP_COMPLETED_GROUP_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_completed_group_message' => env('WHATSAPP_COMPLETED_GROUP_MESSAGE', implode("\n", [
        'New Booking Treatment! 🟢',
        '',
        'HI :staff NEW Booking Treatment from :customer,',
        '',
        'Customer : :customer',
        'Order No : :order_id',
        'Email : :email',
        'Phone : :phone',
        'Order Date : :order_date',
        $waLine,
        'Beautician : :beautician',
        'Appt.Date: :appointment_date',
        'Appt.Time: :appointment_time',
        $waLine,
        'Treatment :',
        ':treatments',
        ':payment_summary',
    ])),
    'whatsapp_completed_beautician_enabled' => filter_var(env('WHATSAPP_COMPLETED_BEAUTICIAN_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_completed_beautician_message' => env('WHATSAPP_COMPLETED_BEAUTICIAN_MESSAGE', implode("\n", [
        'New Booking Treatment! 🟢',
        '',
        'HI :staff — pesanan selesai daripada :customer,',
        '',
        'Customer : :customer',
        'Order No : :order_id',
        'Email : :email',
        'Phone : :phone',
        'Order Date : :order_date',
        $waLine,
        'Beautician : :beautician',
        'Appt.Date: :appointment_date',
        'Appt.Time: :appointment_time',
        $waLine,
        'Treatment :',
        ':treatments',
        ':payment_summary',
    ])),
    'whatsapp_beautician_new_booking_enabled' => filter_var(env('WHATSAPP_BEAUTICIAN_NEW_BOOKING_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_beautician_reminder_enabled' => filter_var(env('WHATSAPP_BEAUTICIAN_REMINDER_ENABLED', true), FILTER_VALIDATE_BOOLEAN),
    'whatsapp_beautician_reminder_minutes' => (int) env('WHATSAPP_BEAUTICIAN_REMINDER_MINUTES', 60),
    'whatsapp_beautician_new_booking_message' => env('WHATSAPP_BEAUTICIAN_NEW_BOOKING_MESSAGE', implode("\n", [
        '📅 *Tempahan Baharu — :store*',
        '',
        'Pelanggan: :customer',
        'Rawatan: :treatment',
        'Tarikh: :date',
        'Masa: :time',
        '',
        'Buka job sheet: :portal_url',
    ])),
    'whatsapp_beautician_reminder_message' => env('WHATSAPP_BEAUTICIAN_REMINDER_MESSAGE', implode("\n", [
        '⏰ *Peringatan Temujanji — :store*',
        '',
        'Pelanggan: :customer',
        'Rawatan: :treatment',
        'Tarikh: :date',
        'Masa: :time',
        '',
        'Buka job sheet: :portal_url',
    ])),
];
