<?php

namespace AestheticCart\Providers;

use AestheticCart\Http\FixSubdirectoryRequest;
use Modules\Core\Providers\XamppCompatibleCacheServiceProvider;
use Modules\Core\Support\WritableStorageBootstrap;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Vite;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\ServiceProvider;
use Jackiedo\DotenvEditor\DotenvEditorServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot(): void
    {
        /*
        |--------------------------------------------------------------------------
        | Configure default String length of the generated migrations
        |--------------------------------------------------------------------------
        | Laravel uses the utf8mb4 character set by default, which includes
        | support for storing "emojis" in the database. if you are running a
        | version of MySQL older than the 5.7.7 release or MariaDB older than
        | the 10.2.2 release, you need to configure the default string length
        | generated by migrations in order for MySQL to create indexes for
        | them.
        */
        Schema::defaultStringLength(191);

        Paginator::useBootstrap();

        $appUrl = FixSubdirectoryRequest::resolvedAppUrl() ?: config('app.url');
        $basePath = FixSubdirectoryRequest::basePath();

        if ($appUrl) {
            URL::forceRootUrl(rtrim($appUrl, '/'));
        }

        if ($basePath !== '') {
            $root = rtrim($basePath, '/');

            config([
                'filesystems.disks.public.url' => $root.'/storage',
                'filesystems.disks.public_storage.url' => $root.'/storage',
                'filesystems.disks.local.url' => $root.'/storage',
            ]);

            Vite::createAssetPathsUsing(
                fn (string $path) => $root.'/'.ltrim($path, '/')
            );
        }

        if (Request::secure()) {
            URL::forceScheme('https');
        }

        if (! config('app.debug')) {
            config(['debugbar.enabled' => false]);
        }
    }


    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register(): void
    {
        WritableStorageBootstrap::apply();
        WritableStorageBootstrap::syncConfigPaths();
        $this->configureProductionStoragePaths();
        $this->configureSessionForSubdirectory();

        if (WritableStorageBootstrap::isLocalEnvironment()) {
            $this->app['config']->set('logging.channels.single.path', WritableStorageBootstrap::logPath());
            $this->app['config']->set('logging.channels.daily.path', WritableStorageBootstrap::logPath());
            $this->app['config']->set('session.files', WritableStorageBootstrap::sessionPath());
            $this->app['config']->set('view.compiled', WritableStorageBootstrap::compiledViewsPath());

            if (filter_var($_ENV['APP_CACHE'] ?? getenv('APP_CACHE'), FILTER_VALIDATE_BOOLEAN)) {
                $this->app['config']->set('cache.stores.file.path', WritableStorageBootstrap::fileCachePath());
                $this->app['config']->set('cache.stores.file.permissions', [
                    'file' => ['public' => 0666, 'private' => 0666],
                    'dir' => ['public' => 0777, 'private' => 0777],
                ]);
            }
        }

        $this->app->register(XamppCompatibleCacheServiceProvider::class);

        if (!config('app.installed')) {
            $this->app->register(DotenvEditorServiceProvider::class);
        }
    }


    private function configureProductionStoragePaths(): void
    {
        if (WritableStorageBootstrap::isLocalEnvironment()) {
            return;
        }

        $this->app['config']->set('logging.channels.single.path', storage_path('logs/laravel.log'));
        $this->app['config']->set('logging.channels.daily.path', storage_path('logs/laravel.log'));
        $this->app['config']->set('session.files', storage_path('framework/sessions'));
        $this->app['config']->set('cache.stores.file.path', storage_path('framework/cache/local-data'));
        $this->app['config']->set('view.compiled', storage_path('framework/views'));
    }


    private function configureSessionForSubdirectory(): void
    {
        $basePath = FixSubdirectoryRequest::basePath();

        if ($basePath !== '') {
            $this->app['config']->set('session.path', $basePath.'/');

            $suffix = str_replace('/', '_', trim($basePath, '/'));

            if ($suffix !== '') {
                $this->app['config']->set('session.cookie', 'aestheticcart_session_'.$suffix);
            }
        }

        $isHttps = (! empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
            || (($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https');

        if ($isHttps) {
            $this->app['config']->set('session.secure', true);
        }
    }
}
